models/Supplier.php
<?php

namespace app\models;

use app\models\query\SupplierQuery;
use Yii;

/**
 * This is the model class for table "supplier".
 *
 * @property int $id
 * @property string $name
 * @property string|null $email
 * @property string $address
 * @property string|null $phone
 *
 * @property Collectiveorder[] $collectiveorders
 * @property Product[] $products
 */
class Supplier extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'supplier';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
        	[['name', 'address', 'email', 'phone'], 'trim'],

            [['name', 'address'], 'required'],
            [['name', 'phone'], 'string', 'max' => 128],
            [['address'], 'string', 'max' => 255],
	        [['email'], 'email'],
	        [['phone'], 'udokmeci\yii2PhoneValidator\PhoneValidator', 'country'=>'CH']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'email' => 'E-Mail',
            'address' => 'Adresse',
            'phone' => 'Telefon Nr.',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCollectiveorders()
    {
        return $this->hasMany(Collectiveorder::className(), ['supplier_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProducts()
    {
        return $this->hasMany(Product::className(), ['supplier_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     * @return SupplierQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SupplierQuery(get_called_class());
    }

}

controllers/ProductController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Product;
use app\models\search\ProductSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Product model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Product model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Product();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Product model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Product model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SupplierController.php
<?php

namespace app\controllers;

use app\models\Product;
use Yii;
use app\models\Supplier;
use app\models\search\SupplierSearch;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SupplierController implements the CRUD actions for Supplier model.
 */
class SupplierController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Supplier models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SupplierSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Supplier model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Supplier model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
	    $supplierModel = new Supplier();

	    if ($supplierModel->load(Yii::$app->request->post()) && $supplierModel->save()) {
		    //product models
		    $numberProducts = count(Yii::$app->request->post('Product', []));

		    for ($i = 0; $i < $numberProducts; $i++) {
		    	$newProduct = new Product();
		    	$newProduct->supplier_id = $supplierModel->id;
			    $products[] = $newProduct;
		    }

		    if (Product::loadMultiple($products, Yii::$app->request->post())
			    && Product::validateMultiple($products)) {
			    /** @var Product $product */
			    foreach ($products as $product) {
				    if (!$product->save(false)) {
					    $this->goBack();
					    Yii::$app->session->setFlash('error', 'Es ist ein Problem beim erstellen der Produkte aufgetaucht.');
				    }
			    }
			    return $this->redirect(['view', 'id' => $supplierModel->id]);
		    }
	    }

		$products = [new Product()];

        return $this->render('create', [
            'supplierModel' => $supplierModel,
	        'productModels' => $products,
        ]);
    }

    /**
     * Updates an existing Supplier model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
	    $supplierModel = $this->findModel($id);
	    $query = Product::find()->andWhere(['supplier_id' => $id]);
	    $productDataProvider = new ActiveDataProvider([
		    'query' => $query,
		    'pagination' => [
			    'pageSize' => 10,
		    ],
	    ]);

	    if ($supplierModel->load(Yii::$app->request->post()) && $supplierModel->save()) {
		    //product models
		    $numberProducts = count(Yii::$app->request->post('Product', []));

		    for ($i = 0; $i < $numberProducts; $i++) {
			    $newProduct = new Product();
			    $newProduct->supplier_id = $supplierModel->id;
			    $products[] = $newProduct;
		    }

		    if (Product::loadMultiple($products, Yii::$app->request->post())
			    && Product::validateMultiple($products)) {
			    /** @var Product $product */
			    foreach ($products as $product) {
				    if (!$product->save(false)) {
					    $this->goBack();
					    Yii::$app->session->setFlash('error', 'Es ist ein Problem beim erstellen der Produkte aufgetaucht.');
				    }
			    }
		    }
		    return $this->goBack();
	    }

	    $products = [new Product()];

	    return $this->render('update', [
		    'supplierModel' => $supplierModel,
		    'productDataProvider' => $productDataProvider,
		    'productModels' => $products
	    ]);
    }

    /**
     * Deletes an existing Supplier model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Supplier model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Supplier the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Supplier::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

views/supplier/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $supplierModel app\models\Supplier */
/* @var $productModels app\models\Product[] */

$this->title = 'Create Supplier';
$this->params['breadcrumbs'][] = ['label' => 'Suppliers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="supplier-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('partials/_form', [
        'supplierModel' => $supplierModel,
	    'productModels' => $productModels,
	    'productDataProvider' => null,
    ]) ?>

</div>

views/supplier/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\SupplierSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Suppliers';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="supplier-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Supplier', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            'name',
            'email:email',
            'address',
            'phone',
            [
	            'format' => 'html',
            	'label' => 'Products',
	            'value' => function ($model) {
    	            $html = '';
					/** @var \app\models\Supplier $model */
		            /** @var \app\models\Product $product */
		            foreach ($model->products as $product) {
		            	$html = $html .
			            Html::beginTag('p') .
			            Html::a($product->name, ['product/view', 'id' => $product->id]) .
			            Html::endTag('p');
		            }
		            return $html;
	            },
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/supplier/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $supplierModel app\models\Supplier */
/* @var $productDataProvider \yii\data\ActiveDataProvider */
/* @var $productModels \app\models\Product[] */

$this->title = 'Update Supplier: ' . $supplierModel->name;
$this->params['breadcrumbs'][] = ['label' => 'Suppliers', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $supplierModel->name, 'url' => ['view', 'id' => $supplierModel->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="supplier-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('partials/_form', [
        'supplierModel' => $supplierModel,
	    'productDataProvider' => $productDataProvider,
	    'productModels' => $productModels,
    ]) ?>

</div>

views/supplier/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Supplier */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Suppliers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="supplier-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'email:email',
            'address',
            'phone',
        ],
    ]) ?>

</div>